### ISSUE TITLE
Unhandle exception when executing }settings

### ISSUE THREAD

**Issue by nandub** [brussell98/BrussellBot#17]
On a Mirai vanila execution I get this error on the console when executing `}settings` command.

```
}settings 
Unhandled rejection Error: 403 FORBIDDEN
    at IncomingMessage.resp.once.err (/Users/nandub/development/source/Mirai/node_modules/eris/lib/rest/RequestHandler.js:149:35)
    at IncomingMessage.g (events.js:286:16)
    at emitNone (events.js:91:20)
    at IncomingMessage.emit (events.js:185:7)
    at endReadableNT (_stream_readable.js:975:12)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)
```

I can see the `}settings` usage message from discord but I see the above on the console.

**Comment by nandub** [comment]
This was resolved by adding `Manage Messages`.
