### ISSUE TITLE
SyntaxError: Unexpected token )

### ISSUE THREAD

**Issue by itsfolf** [brussell98/BrussellBot#9]
```
2016-05-28T13:52:48.014361+00:00 app[bot.1]: /app/BrussellBot.js:314
2016-05-28T13:52:48.014421+00:00 app[bot.1]: );
2016-05-28T13:52:48.014423+00:00 app[bot.1]: ^
2016-05-28T13:52:48.014432+00:00 app[bot.1]: SyntaxError: Unexpected token )
2016-05-28T13:52:48.014432+00:00 app[bot.1]:     at Object.exports.runInThisContext (vm.js:53:16)
2016-05-28T13:52:48.014433+00:00 app[bot.1]:     at Module._compile (module.js:513:28)
2016-05-28T13:52:48.014438+00:00 app[bot.1]:     at Object.Module._extensions..js (module.js:550:10)
2016-05-28T13:52:48.014439+00:00 app[bot.1]:     at Module.load (module.js:458:32)
2016-05-28T13:52:48.014439+00:00 app[bot.1]:     at tryModuleLoad (module.js:417:12)
2016-05-28T13:52:48.014440+00:00 app[bot.1]:     at Function.Module._load (module.js:409:3)
2016-05-28T13:52:48.014440+00:00 app[bot.1]:     at Function.Module.runMain (module.js:575:10)
2016-05-28T13:52:48.014441+00:00 app[bot.1]:     at startup (node.js:160:18)
2016-05-28T13:52:48.014441+00:00 app[bot.1]:     at node.js:449:3

```

```
bot.on("serverCreated", server => {
    if (db.serverIsNew(server)) {
        console.log(cGreen("Joined server: ") + server.name);
        if (config.banned_server_ids && config.banned_server_ids.includes(server.id)) {
            console.log(cRed("Joined server but it was on the ban list") + `: ${server.name}`);
            bot.sendMessage(server.defaultChannel, ":name_badge: This server is banned because of rule breaking :name_badge:");
            setTimeout(()=>{bot.leaveServer(server);},1000);
        } else {
            db.addServerToTimes(server);
            bot.sendMessage(server.defaultChannel, `👋🏻 Hi! I'm **${bot.user.username.replace(/@/g, '@\u200b')}**\nYou can use **\`${config.command_prefix}help\`** to see what I can do.\nMod/Admin commands *including bot settings* can be viewed with **\`${config.mod_command_prefix}help\`**\nFor help, feedback, bugs, info, changelogs, etc. go to **<https://discord.gg/0kvLlwb7slG3XCCQ>**`);
            db.addServer(server);
    }

        if (!server.defaultChannel.permissionsOf(bot.user).hasPermission('manageMessages')) {
                bot.sendMessage(server.defaultChannel, ":warning: :no_entry: The bot doesn't have the asked permissions, some errors can be ocurred :no_entry: :warning:");
        }
}
);
```

PS Line 314 is the last one wich contains "(;"

**Comment by brussell98** [comment]
1. What version of Node are you using? The bot requires 6+. You can check by doing `node -v`
2. Try updating to the newest version of the bot.

**Comment by itsfolf** [comment]
I don't know what it was, I justed copied the code from here again, and added my method again too, and it worked.
